[package]
name = "proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
lazy_static = "1.4.0"
quote = "1.0.35"
syn = "2.0.51"
value-ty = { version = "0.1.0", path = "../value-ty" }
